name: 'Datadog Workflow Metrics'
description: 'Reports data on the workflow to datadog'
inputs:
  datadog-metric-prefix:
    description: 'A prefix for your datadog metrics'
    required: false
    default: 'github.action'
  metrics-type:
    description: '"velocity" or "job_metrics" depending on the desired metrics to be collected'
    required: true
  teams:
    description: 'An array of teams to tag the time to merge metric with'
    required: false
    default: '[]'
  tagged-branches:
    description: 'If provided enables tagging for specified branches. Metrics are tagged with branch:{branch} or branch:other'
    required: false
    default: '[]'
  custom-tags:
    description: 'A list of tags to attach to the metrics. In the format of "[TAG1:VALUE1,TAG2:VALUE2,..]".'
    required: false
    default: '[]'

runs:
  using: "composite"
  steps:
    - name: Install required libraries for gems
      shell: bash
      run: |
        gem install octokit -v 4.25.1
        gem install dogapi -v 1.45.0
    - name: Export extra data
      shell: bash
      run: |
        if [ "${{ inputs.metrics-type }}" == "velocity" ]; then
          echo "PR_NUMBER=${{github.event.pull_request.number}}" >> $GITHUB_ENV
          echo "ACTION=${{github.event.action}}" >> $GITHUB_ENV
        else
          echo "ACTION=${{ inputs.metrics-type }}" >> $GITHUB_ENV
        fi
    - id: metric
      shell: bash
      run: |
        ruby ${{ github.action_path }}/report_github_metrics.rb ${{github.repository}} ${{github.run_id}} ${{ inputs.datadog-metric-prefix }} '${{ inputs.teams }}' '${{ inputs.tagged-branches }}' '${{ inputs.custom-tags }}'
